name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches: [ "main" ]   # Se despliega cada vez que hagas push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Construir proyecto
      - name: Build project
        run: npm run build

      # 5️⃣ Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.FROST_BITE_PW }}
          publish_dir: ./dist          # Carpeta generada por Vite
          publish_branch: gh-pages     # Rama donde se publican los archivos
